### ISSUE TITLE
Undefined index SERVER_ADDR in about.blade.php

### ISSUE THREAD

**Issue by pierDipi** [simonecosci/wms#4]
## Description 

Undefined index SERVER_ADDR in about window.

## Step to reproduce
First login as admin, then click on: options -> about.
The obtained red window, on top, shows the following message : 
`message: Undefined index: SERVER_ADDR (View: wms\resources\views\admin\about.blade.php).`

Note: If the window doesn't appear refresh the page and try again.

**Comment by simonecosci** [comment]
Thank you, your PR has been merged in master branch
